# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 225d3eb7064432da97dbdd9bd2835f73bf0497d0b5ac0645c168e2baf2c1a970e16c562917449627084bff7f9ba5d1fdeb3d0a85ab21c45f223429cc24a13dca

test:
  secret_key_base: 8ea23a465886fd68a913bf76321b8ad7dc2ae36db470eb0ee6af08c3af570d3af373f6a68bf21e5df79fec804fc984a77d326f05b70cabcd709ea9fe44952507

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
